-- ============================================================================
-- Migration 0001 — Initial schema for japanauto.ca
-- ============================================================================
-- Cloudflare D1 (SQLite). Apply via:
--   wrangler d1 migrations apply japanauto --local
--   wrangler d1 migrations apply japanauto --remote
--
-- Covers:
--   ADR-0001 stack selection (D1 raw SQL, no ORM)
--   ADR-0002 sitemap & buyer model (no /new-cars/* in listings, see featured_slots)
--   ADR-0003 direct contact display (no chat tables on MVP)
--   ADR-0004 edge geolocation (cities + city_aliases)
--   ADR-0005 single domain (no tenant/realm tables)
--   ADR-0006 city-bound primary flow (cities.status: active|planned|paused)
--   ADR-0007 3-step navigation + featured/boost monetization + age cap
--
-- Conventions:
--   * All money fields — INTEGER, cents CAD.
--   * Timestamps — INTEGER, Unix seconds (use unixepoch()).
--   * IDs — TEXT (cuid2 / nanoid generated by Workers).
--   * Booleans — INTEGER (0/1).
--   * Province — ISO codes (AB|BC|ON|QC|MB|SK|NS|NB|NL|PE|YT|NT|NU).
--   * VIN — 17 chars, ISO 3779, validated by zod (CHECK length only).
--   * Year cap — strftime('%Y','now') - 10 .. +1 (rolling, no annual migration).
-- ============================================================================

PRAGMA foreign_keys = ON;

-- ============================================================================
-- DEALERS (sellers — both type='dealer' and type='salvage_yard')
-- ============================================================================
CREATE TABLE dealers (
  id              TEXT PRIMARY KEY,
  type            TEXT NOT NULL CHECK (type IN ('dealer', 'salvage_yard')),
  name            TEXT NOT NULL,
  slug            TEXT NOT NULL,
  email           TEXT NOT NULL,
  password_hash   TEXT NOT NULL,
  phone           TEXT,                              -- E.164 +14035551234
  website         TEXT,
  description     TEXT,

  -- Address (Canada)
  address_line1   TEXT,
  address_line2   TEXT,
  city            TEXT NOT NULL,                     -- city-political
  province        TEXT NOT NULL CHECK (province IN
                    ('AB','BC','ON','QC','MB','SK','NS','NB','NL','PE','YT','NT','NU')),
  postal_code     TEXT,                              -- A1A 1A1 (validated by zod)
  country         TEXT NOT NULL DEFAULT 'CA' CHECK (country = 'CA'),
  lat             REAL,
  lng             REAL,

  -- Business identifiers
  business_number TEXT,                              -- CRA BN
  gst_number      TEXT,                              -- GST/HST registration
  amvic_number    TEXT,                              -- mandatory if type='dealer' AND province='AB'

  -- Operational state
  verified              INTEGER NOT NULL DEFAULT 0 CHECK (verified IN (0, 1)),
  subscription_tier     TEXT NOT NULL DEFAULT 'free'
                          CHECK (subscription_tier IN ('free', 'pro')),
  subscription_status   TEXT CHECK (subscription_status IS NULL OR subscription_status IN
                          ('trialing','active','past_due','canceled','incomplete','incomplete_expired','unpaid')),
  stripe_customer_id    TEXT,

  -- Anti-spam (per anti-spam-policy)
  daily_listing_count   INTEGER NOT NULL DEFAULT 0,
  daily_listing_reset_at INTEGER,                    -- Unix timestamp of next 00:00 UTC reset

  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);

CREATE UNIQUE INDEX idx_dealers_slug ON dealers (slug);
CREATE UNIQUE INDEX idx_dealers_email ON dealers (email);
CREATE INDEX idx_dealers_city_province ON dealers (city, province, type);
CREATE INDEX idx_dealers_stripe_customer ON dealers (stripe_customer_id);

-- AMVIC enforcement is at application layer (Workers + zod):
-- IF type='dealer' AND province='AB' THEN amvic_number IS NOT NULL.

-- ============================================================================
-- MAKES (Japanese brands whitelist — see japanese-brands-whitelist.md)
-- ============================================================================
CREATE TABLE makes (
  id          INTEGER PRIMARY KEY,
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL,
  origin      TEXT NOT NULL DEFAULT 'japan' CHECK (origin = 'japan'),
  -- Commercial weight order for brand grid (1..9). NULL = not in MVP grid.
  display_order INTEGER
);

CREATE UNIQUE INDEX idx_makes_slug ON makes (slug);

-- ============================================================================
-- MODELS
-- ============================================================================
CREATE TABLE models (
  id          INTEGER PRIMARY KEY,
  make_id     INTEGER NOT NULL REFERENCES makes (id) ON DELETE RESTRICT,
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL,
  year_start  INTEGER,
  year_end    INTEGER,
  body_types  TEXT,                                  -- JSON array, validated by zod
  UNIQUE (make_id, slug)
);

CREATE INDEX idx_models_make ON models (make_id);

-- ============================================================================
-- CITIES (CMA-only — see cities-list.md)
-- ============================================================================
CREATE TABLE cities (
  id              INTEGER PRIMARY KEY,
  slug            TEXT NOT NULL,                     -- 'toronto', 'calgary', ...
  name            TEXT NOT NULL,                     -- 'Toronto', 'Calgary', ...
  province        TEXT NOT NULL CHECK (province IN
                    ('AB','BC','ON','QC','MB','SK','NS','NB','NL','PE','YT','NT','NU')),
  population_cma  INTEGER,                           -- 2021 census numbers (re-verify pre-prod)
  lat             REAL,
  lng             REAL,
  tier            INTEGER NOT NULL CHECK (tier IN (1, 2, 3)),
  status          TEXT NOT NULL DEFAULT 'planned'
                    CHECK (status IN ('active', 'planned', 'paused'))
);

CREATE UNIQUE INDEX idx_cities_slug ON cities (slug);
-- Composite UNIQUE retained for legacy compatibility — both can coexist.
CREATE UNIQUE INDEX idx_cities_slug_province ON cities (slug, province);
CREATE INDEX idx_cities_status_tier ON cities (status, tier);

-- ============================================================================
-- CITY_ALIASES (city-political → CMA-slug for edge geolocation, ADR-0007)
-- ============================================================================
CREATE TABLE city_aliases (
  city_political  TEXT NOT NULL,                     -- 'mississauga', 'gatineau', ...
  cma_slug        TEXT NOT NULL REFERENCES cities (slug) ON DELETE CASCADE,
  -- province is the user's province (request.cf.region), not the CMA's:
  -- e.g. 'gatineau' lives in QC but maps to CMA 'ottawa' (which sits in ON).
  province        TEXT NOT NULL CHECK (province IN
                    ('AB','BC','ON','QC','MB','SK','NS','NB','NL','PE','YT','NT','NU')),
  PRIMARY KEY (city_political, province)
);

CREATE INDEX idx_city_aliases_cma ON city_aliases (cma_slug, province);

-- ============================================================================
-- LISTINGS (used cars — `new` is served via featured_slots, see ADR-0007)
-- ============================================================================
-- Year cap rolling: strftime('%Y','now') — current year as string.
-- Lower bound: currentYear - 10 (used age cap).
-- Upper bound: currentYear + 1 (early model-year release).
-- ============================================================================
CREATE TABLE listings (
  id              TEXT PRIMARY KEY,
  dealer_id       TEXT NOT NULL REFERENCES dealers (id) ON DELETE CASCADE,

  -- Identity
  make_id         INTEGER NOT NULL REFERENCES makes (id) ON DELETE RESTRICT,
  model_id        INTEGER NOT NULL REFERENCES models (id) ON DELETE RESTRICT,
  -- Static sanity bounds; rolling 10-year age cap enforced by triggers below
  -- (SQLite forbids non-deterministic strftime() in CHECK).
  year            INTEGER NOT NULL CHECK (year BETWEEN 1990 AND 2100),
  trim            TEXT,
  vin             TEXT NOT NULL CHECK (length(vin) = 17),

  -- Vehicle Schema.org fields
  body_type       TEXT CHECK (body_type IS NULL OR body_type IN
                    ('sedan','suv','coupe','wagon','hatchback','convertible',
                     'minivan','pickup','crossover')),
  fuel_type       TEXT CHECK (fuel_type IS NULL OR fuel_type IN
                    ('gasoline','hybrid','plugin_hybrid','electric','diesel')),
  transmission    TEXT CHECK (transmission IS NULL OR transmission IN
                    ('automatic','manual','cvt','dct')),
  drivetrain      TEXT CHECK (drivetrain IS NULL OR drivetrain IN ('fwd','rwd','awd','4wd')),
  doors           INTEGER CHECK (doors IS NULL OR (doors BETWEEN 2 AND 5)),
  seats           INTEGER CHECK (seats IS NULL OR (seats BETWEEN 2 AND 9)),
  engine_displacement REAL CHECK (engine_displacement IS NULL OR (engine_displacement BETWEEN 0.5 AND 8.0)),
  color_exterior  TEXT,
  color_interior  TEXT,

  -- Listing details
  mileage         INTEGER NOT NULL CHECK (mileage BETWEEN 0 AND 1000000),  -- km
  condition       TEXT NOT NULL CHECK (condition IN
                    ('used_excellent','used_good','used_fair')),
  price           INTEGER NOT NULL CHECK (price BETWEEN 0 AND 100000000),  -- cents CAD, max 1M CAD
  price_currency  TEXT NOT NULL DEFAULT 'CAD' CHECK (price_currency = 'CAD'),
  negotiable      INTEGER NOT NULL DEFAULT 1 CHECK (negotiable IN (0, 1)),

  -- Location (city-political; mapped to CMA via city_aliases at query time)
  city            TEXT NOT NULL,
  province        TEXT NOT NULL CHECK (province IN
                    ('AB','BC','ON','QC','MB','SK','NS','NB','NL','PE','YT','NT','NU')),

  -- SEO
  slug            TEXT NOT NULL,
  title           TEXT NOT NULL,                     -- max 120 by zod
  description     TEXT,                              -- max 5000 by zod

  -- Lifecycle (see listing-lifecycle.md)
  status          TEXT NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft','active','sold','expired','flagged')),
  expires_at      INTEGER,                           -- 90 days after publish by default
  sold_at         INTEGER,                           -- when status set to 'sold'

  -- Engagement metrics (for sort + analytics)
  view_count      INTEGER NOT NULL DEFAULT 0,
  contact_count   INTEGER NOT NULL DEFAULT 0,        -- "Show contact" reveals

  -- Monetization (ADR-0007 boost-plan)
  boost_until        INTEGER,                        -- Unix ts; > unixepoch() = active boost
  boost_paid_cents   INTEGER NOT NULL DEFAULT 0,     -- cumulative (for sort within boosted tier)

  -- Reserved: legacy `featured_until` removed in favor of featured_slots table.
  -- Sponsored top-of-list slots live in `featured_slots`, not on individual listings.

  -- Moderation
  flagged_reason  TEXT,

  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);

CREATE UNIQUE INDEX idx_listings_slug ON listings (slug);
CREATE UNIQUE INDEX idx_listings_vin ON listings (vin);
CREATE INDEX idx_listings_filter
  ON listings (make_id, model_id, year, city, province, status);
CREATE INDEX idx_listings_dealer_status ON listings (dealer_id, status);
CREATE INDEX idx_listings_status_expires ON listings (status, expires_at);
CREATE INDEX idx_listings_boost ON listings (boost_until, boost_paid_cents)
  WHERE status = 'active' AND boost_until IS NOT NULL;
CREATE INDEX idx_listings_catalog_sort
  ON listings (city, make_id, model_id, status, created_at DESC)
  WHERE status = 'active';

-- ============================================================================
-- FEATURED_SLOTS (long-term sponsored slots for official dealers, ADR-0007)
-- ============================================================================
-- One active slot per (make_id, city) at a time. Top of /used-cars/[make]/[model]/[city]/.
-- Promotes a NEW vehicle from official dealer; bypasses listings.year age cap.
-- ============================================================================
CREATE TABLE featured_slots (
  id                  TEXT PRIMARY KEY,
  dealer_id           TEXT NOT NULL REFERENCES dealers (id) ON DELETE CASCADE,
  make_id             INTEGER NOT NULL REFERENCES makes (id) ON DELETE RESTRICT,
  model_id            INTEGER REFERENCES models (id) ON DELETE SET NULL, -- NULL = applies to all models of make
  city                TEXT NOT NULL,                 -- CMA slug, FK enforced via app layer
  province            TEXT NOT NULL CHECK (province IN
                        ('AB','BC','ON','QC','MB','SK','NS','NB','NL','PE','YT','NT','NU')),

  -- Promo creative (NEW vehicle, MSRP)
  promo_title         TEXT NOT NULL,                 -- "New 2026 Toyota Corolla LE"
  promo_msrp_cents    INTEGER NOT NULL CHECK (promo_msrp_cents BETWEEN 0 AND 100000000),
  promo_image_id      TEXT,                          -- Cloudflare Images id (R2 key in media)
  promo_url           TEXT NOT NULL,                 -- dealer landing page (CTA "Visit dealer website →")
  disclosure          TEXT NOT NULL,                 -- "Sponsored by Maple Toyota — official Toyota dealer in Calgary"

  -- Contract window
  active_from         INTEGER NOT NULL,              -- Unix ts
  active_until        INTEGER NOT NULL,              -- Unix ts
  contract_paid_cents INTEGER NOT NULL DEFAULT 0,    -- audit; not used for sort (only one slot active per make/city)

  status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','active','paused','ended')),

  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL
);

CREATE INDEX idx_featured_slots_lookup
  ON featured_slots (make_id, city, status, active_until);
CREATE INDEX idx_featured_slots_dealer
  ON featured_slots (dealer_id, status);

-- One ACTIVE slot per (make, city, model-or-all) at any moment — enforced at app layer
-- because SQLite cannot do UNIQUE filtered indexes that cover overlapping time windows.
-- Workers logic: SELECT ... WHERE status='active' AND active_until > unixepoch() LIMIT 1.

-- ============================================================================
-- BOOST_ORDERS (audit trail for boost-plan purchases, ADR-0007)
-- ============================================================================
-- Every Stripe boost charge writes a row here. Used for accounting,
-- dispute resolution, and computing listings.boost_paid_cents totals.
-- ============================================================================
CREATE TABLE boost_orders (
  id                  TEXT PRIMARY KEY,
  listing_id          TEXT NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
  dealer_id           TEXT NOT NULL REFERENCES dealers (id) ON DELETE CASCADE,
  amount_cents        INTEGER NOT NULL CHECK (amount_cents > 0),
  duration_days       INTEGER NOT NULL CHECK (duration_days BETWEEN 1 AND 90),
  stripe_payment_id   TEXT,                          -- pi_... from Stripe
  applied_at          INTEGER NOT NULL,              -- Unix ts when boost_until was extended
  expires_at          INTEGER NOT NULL,              -- applied_at + duration_days
  status              TEXT NOT NULL DEFAULT 'paid'
                        CHECK (status IN ('paid','refunded','disputed')),
  created_at          INTEGER NOT NULL
);

CREATE INDEX idx_boost_orders_listing ON boost_orders (listing_id, expires_at);
CREATE INDEX idx_boost_orders_dealer ON boost_orders (dealer_id, created_at DESC);
CREATE UNIQUE INDEX idx_boost_orders_stripe ON boost_orders (stripe_payment_id)
  WHERE stripe_payment_id IS NOT NULL;

-- ============================================================================
-- PARTS (from salvage_yards — no age cap, see ADR-0007)
-- ============================================================================
CREATE TABLE parts (
  id                  TEXT PRIMARY KEY,
  dealer_id           TEXT NOT NULL REFERENCES dealers (id) ON DELETE CASCADE,
  -- enforced at app layer: dealer.type must equal 'salvage_yard'

  title               TEXT NOT NULL,
  category            TEXT NOT NULL CHECK (category IN
                        ('engine','transmission','body','electrical','interior','exterior',
                         'suspension','brakes','wheels_tires','exhaust','cooling','fuel_system',
                         'glass','lights','accessories','other')),
  subcategory         TEXT,
  description         TEXT,

  -- Compatibility (JSON arrays — validated by zod, parts-compatibility.md)
  compatible_makes    TEXT,                          -- JSON array of make slugs
  compatible_models   TEXT,                          -- JSON array of model slugs
  compatible_years    TEXT,                          -- JSON array of integers (no age cap for parts)

  -- Part identity
  part_number         TEXT,
  oem_number          TEXT,
  condition           TEXT NOT NULL CHECK (condition IN ('new','used','refurbished','oem')),
  warranty_days       INTEGER CHECK (warranty_days IS NULL OR warranty_days >= 0),

  -- Pricing
  price               INTEGER NOT NULL CHECK (price BETWEEN 0 AND 100000000),
  price_currency      TEXT NOT NULL DEFAULT 'CAD' CHECK (price_currency = 'CAD'),

  slug                TEXT NOT NULL,
  status              TEXT NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','active','sold','expired','flagged')),

  view_count          INTEGER NOT NULL DEFAULT 0,
  contact_count       INTEGER NOT NULL DEFAULT 0,

  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL
);

CREATE UNIQUE INDEX idx_parts_slug ON parts (slug);
CREATE INDEX idx_parts_dealer_status ON parts (dealer_id, status);
CREATE INDEX idx_parts_category_status ON parts (category, status);

-- ============================================================================
-- MEDIA (images for listings, parts, dealers, featured_slots)
-- ============================================================================
CREATE TABLE media (
  id              TEXT PRIMARY KEY,
  entity_type     TEXT NOT NULL CHECK (entity_type IN
                    ('listing','part','dealer','featured_slot')),
  entity_id       TEXT NOT NULL,                     -- references owning row, FK enforced at app layer (polymorphic)
  r2_key          TEXT NOT NULL,                     -- e.g. "listings/<id>/01.jpg"
  cf_image_id     TEXT,                              -- Cloudflare Images variant id, optional
  alt_text        TEXT,                              -- mandatory for SEO; enforced at app layer
  width           INTEGER,
  height          INTEGER,
  display_order   INTEGER NOT NULL DEFAULT 0,
  is_primary      INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
  bytes           INTEGER,                           -- file size for quota tracking
  created_at      INTEGER NOT NULL
);

CREATE INDEX idx_media_entity ON media (entity_type, entity_id, display_order);
CREATE UNIQUE INDEX idx_media_r2_key ON media (r2_key);
-- One primary per entity — enforced at app layer (SQLite has no partial UNIQUE on multi-col).

-- ============================================================================
-- AUTH: refresh tokens (JWT short-lived + refresh token rotation)
-- ============================================================================
-- Access JWT lives ~15 min in cookie/header.
-- Refresh tokens stored hashed; rotation on use.
-- ============================================================================
CREATE TABLE refresh_tokens (
  id              TEXT PRIMARY KEY,
  dealer_id       TEXT NOT NULL REFERENCES dealers (id) ON DELETE CASCADE,
  token_hash      TEXT NOT NULL,                     -- sha256 of secret
  user_agent      TEXT,
  ip_address      TEXT,
  issued_at       INTEGER NOT NULL,
  expires_at      INTEGER NOT NULL,                  -- 30 days
  revoked_at      INTEGER,
  rotated_to      TEXT REFERENCES refresh_tokens (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX idx_refresh_tokens_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_tokens_dealer ON refresh_tokens (dealer_id, expires_at);

-- ============================================================================
-- AUTH: email verification + password reset tokens
-- ============================================================================
CREATE TABLE verification_tokens (
  id              TEXT PRIMARY KEY,
  dealer_id       TEXT NOT NULL REFERENCES dealers (id) ON DELETE CASCADE,
  purpose         TEXT NOT NULL CHECK (purpose IN ('email_verify','password_reset')),
  token_hash      TEXT NOT NULL,
  expires_at      INTEGER NOT NULL,
  consumed_at     INTEGER,
  created_at      INTEGER NOT NULL
);

CREATE UNIQUE INDEX idx_verification_tokens_hash ON verification_tokens (token_hash);
CREATE INDEX idx_verification_tokens_dealer ON verification_tokens (dealer_id, purpose, expires_at);

-- ============================================================================
-- CONTACT_REVEALS (anti-scraping audit + abuse detection, ADR-0003)
-- ============================================================================
-- One row per "Show contact" click. Used to detect scraping patterns
-- and rate-limit anonymous reveals.
-- ============================================================================
CREATE TABLE contact_reveals (
  id              TEXT PRIMARY KEY,
  entity_type     TEXT NOT NULL CHECK (entity_type IN ('listing','part','dealer')),
  entity_id       TEXT NOT NULL,
  ip_hash         TEXT NOT NULL,                     -- sha256(ip + daily-salt)
  user_agent_hash TEXT,
  revealed_at     INTEGER NOT NULL
);

CREATE INDEX idx_contact_reveals_entity ON contact_reveals (entity_type, entity_id, revealed_at);
CREATE INDEX idx_contact_reveals_ip ON contact_reveals (ip_hash, revealed_at);

-- ============================================================================
-- TRIGGERS: rolling 10-year age cap on listings.year (ADR-0007)
-- ============================================================================
-- Implemented as triggers because SQLite forbids non-deterministic strftime()
-- in CHECK constraints. The rolling window shifts automatically with system
-- clock — no annual schema migration needed.
--
-- Lower bound: currentYear - 10  (e.g. 2026 → year >= 2016)
-- Upper bound: currentYear + 1   (early model-year release allowance)
--
-- Application layer (zod) duplicates this rule for friendly 422 errors;
-- the trigger is the last line of defence at DB level.
-- ============================================================================
CREATE TRIGGER trg_listings_age_cap_insert
BEFORE INSERT ON listings
BEGIN
  SELECT RAISE(ABORT, 'listings.year out of rolling window (currentYear-10 .. currentYear+1)')
  WHERE NEW.year < CAST(strftime('%Y','now') AS INTEGER) - 10
     OR NEW.year > CAST(strftime('%Y','now') AS INTEGER) + 1;
END;

CREATE TRIGGER trg_listings_age_cap_update
BEFORE UPDATE OF year ON listings
BEGIN
  SELECT RAISE(ABORT, 'listings.year out of rolling window (currentYear-10 .. currentYear+1)')
  WHERE NEW.year < CAST(strftime('%Y','now') AS INTEGER) - 10
     OR NEW.year > CAST(strftime('%Y','now') AS INTEGER) + 1;
END;

-- featured_slots table is intentionally exempt: it advertises NEW vehicles
-- (model_year >= currentYear), which by definition fall outside the used-cap.

-- ============================================================================
-- TRIGGERS: keep updated_at fresh on row modifications
-- ============================================================================
CREATE TRIGGER trg_dealers_updated_at
AFTER UPDATE ON dealers FOR EACH ROW
BEGIN
  UPDATE dealers SET updated_at = CAST(strftime('%s','now') AS INTEGER) WHERE id = NEW.id AND updated_at = OLD.updated_at;
END;

CREATE TRIGGER trg_listings_updated_at
AFTER UPDATE ON listings FOR EACH ROW
BEGIN
  UPDATE listings SET updated_at = CAST(strftime('%s','now') AS INTEGER) WHERE id = NEW.id AND updated_at = OLD.updated_at;
END;

CREATE TRIGGER trg_parts_updated_at
AFTER UPDATE ON parts FOR EACH ROW
BEGIN
  UPDATE parts SET updated_at = CAST(strftime('%s','now') AS INTEGER) WHERE id = NEW.id AND updated_at = OLD.updated_at;
END;

CREATE TRIGGER trg_featured_slots_updated_at
AFTER UPDATE ON featured_slots FOR EACH ROW
BEGIN
  UPDATE featured_slots SET updated_at = CAST(strftime('%s','now') AS INTEGER) WHERE id = NEW.id AND updated_at = OLD.updated_at;
END;
