/**
 * AUTO-GENERATED by scripts/generate-csp-hashes.mjs — do not edit by hand.
 * SHA-256 hashes of every unique executable inline <script> body in dist/.
 * Consumed by functions/_middleware.ts to build the script-src directive
 * without 'unsafe-inline' (audit #18). Regenerated on every `npm run build`.
 */
export const SCRIPT_HASHES: readonly string[] = [
  'sha256-+MpmbNqhVG2jZtQ7ftYNBXqCSWKqtfpVV+d5lW1gcYM=',
  'sha256-+j76kFy8YKDcpIdD725GIwg7hMoy50FPTHH5fwUFyZE=',
  'sha256-0eX8PHo/nwPZntN8wsuVA7YFW2Hr/GhEXHzCBos6cow=',
  'sha256-1fufWevoRjgHOx9bB1SrrywJxkDxpx0/UfkIkSgtMrU=',
  'sha256-4bLF2xA/ZUJYWmkbEZvBymQ53uPogmKqygTM2AhXQ8I=',
  'sha256-7sQ4Dumq0QpsW3ohac+SbwIcA87AT3hFQllFDqkJN7k=',
  'sha256-C5ylC869dOmKO4ITcZbVKu5S+2AsGBMW5/zkXuTwdmo=',
  'sha256-I+9bRy3pRBrWDW9JJqK2M2M5aiUn3/r2ZM14u6PQi74=',
  'sha256-TrsoRsJT9MsLHHBBkfWCrs7+z5XGwvz7bfKtD1Cx7eQ=',
  'sha256-UmKSxAh1zXXpSABy9ZWWByUUwMMjZwdX4Q43iiseg/I=',
  'sha256-UpnMB2Zn/kkZW9G0iGjlXSxY5U5ZNLLV4VMLLhAkYFU=',
  'sha256-W2N2VPf9RnGELWc28jwC1XETAJ0SKGWJYHCWCSHE4g8=',
  'sha256-XKDwedQw7OzTgAZpI8qDXN1XGtEShVyaHHAMZkdG3KI=',
  'sha256-btjWeb1yzRrcijKcjFFTc6fmL1MfApKBZyUHie4d8yQ=',
  'sha256-djX9FyZZDgJNltSnvBxOrPzo2xRoDVRvypUWqzOp+ZU=',
  'sha256-eHRz9EBS7/Q3ovG8Gx1LwnNwO3KYvAQid1AwfrL8Snw=',
  'sha256-k88iyx1/GNzdTJaD/aBBKZiNGFFtU3+czWawfz8t7d4=',
  'sha256-n+ltotczLRMbiUvB4LwG7ojyKzPjt4KT8h2H4MKHIoU=',
  'sha256-osoV/qZGCL4tBGGRJrR88D3tQKJKWcy4+MAYuavvZj8=',
  'sha256-pjRlwl5xBmMTIEpXQ5KcTsG30hKh0EdtSZ9GuiO7MWs=',
  'sha256-u+GsEYo5xKu5gOeIKwDJPsq0dVfsGW87/KP9+EQcjiU=',
  'sha256-vNvza+oteQZ7bRGGV/7rGyzf5024BJeahpTlANGISiU=',
  'sha256-wNFeat/IlwgAtYRhT3mlZVVasHz39yuBuj6PvWgsJ9A=',
  'sha256-xBC6O3v6r+vmTB00mY8GQX4WDX/Jx3joVlt1T359C0M=',
  'sha256-ys94+zpQ9o8owo1uGZsqDIwVNZYMLbj4Ve78vV+shF4=',
];
